version: '3.7'

networks:
  default:
    external:
      name: sagemaker-local

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    container_name: minio
    command: server /data
    volumes:
      - ./data/minio:/data
    restart: unless-stopped
    env_file: config.env
  rl_coach:
    image: mattcamp/dr-coach
    env_file: config.env
    container_name: coach
    volumes:
    - '//var/run/docker.sock:/var/run/docker.sock'
    - './src/rl_coach_2020_v2:/deepracer/rl_coach'
    - '/robo/container:/robo/container'
    depends_on:
    - minio
  # kinesis:
  #   image: vsouza/kinesis-local:latest
  #   command: --port 4567 --ssl
  #   restart: always
  #   container_name: kinesis
  #   ports:
  #     - "4567:4567"
  robomaker:
    image: mattcamp/robomaker:cpu
    command: ["${ROBOMAKER_COMMAND}"]
    volumes:
      - ./data/robomaker:/root/.ros/
    ports:
      - "8080:5900"
    container_name: robomaker
    restart: unless-stopped
    env_file: config.env
    depends_on:
    - rl_coach
    # - kinesis
